version: '3.8'
services:
  mongodb:
    image: mongo:latest
    container_name: mongodb-evaluator
    restart: always
    environment:
      MONGODB_INITDB_ROOT_USERNAME: user
      MONGODB_INITDB_ROOT_PASSWORD: pass
      MONGO_INITDB_DATABASE: nyc
    ports:
      - "27017:27017"

  mongo_seed:
    image: mongo:latest
    links:
      - mongodb
    volumes:
      - ./mongo-seed:/mongo-seed
    command:
      /mongo-seed/import.sh


